apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scores-app.fullname" . }}
  labels:
    {{- include "scores-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "scores-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "scores-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
